    ### Spring properties
    # Service registers under this name
    spring:
      application:
        name: user-t4k-microservice
      datasource:
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password:  
        driver-class-name: org.h2.Driver

    # Discovery Server Access
    eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:1111/eureka/

    # HTTP Server (Tomcat) Port
    server: 
      port: 2222
